### ISSUE TITLE
NoSuchMethodError on org.eclipse.jdt.internal.core.JavaProject.internalDefaultRootModules

### ISSUE THREAD

**Issue by rgrunber** [microsoft/vscode-gradle#1651]
See https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/3401.

> Here's the signature change : https://github.com/eclipse-jdt/eclipse.jdt.core/commit/831cde98bf162d5164b87e836879ce8c0d0d5bcb#diff-00562771497dd0965664c44810dd765ed272139b61ad69619cc3af891164c06bR749-R818
>
> Here's where the gradle build server uses it : https://github.com/microsoft/vscode-gradle/blob/6c31daa0d812a0b07868ee6103d8feb4cac57568/extension/jdtls.ext/com.microsoft.gradle.bs.importer/src/com/microsoft/java/builder/jdtbuilder/ClasspathJrt.java#L278
>
> Basically, the release version needs to be passed in as an argument. This should be filed at https://github.com/microsoft/vscode-gradle ...

**Comment by DrewCCannedy** [comment]
I'm experiencing the same issue. Workaround for me was reverting "Language Support for Java(TM) by Red Hat" to the previous version.

This was causing compiler warnings to not appear which frankly makes the extension unusable.

**Comment by negativems** [comment]
Same issue here, VSCode dont compiles while debugging.

It stuck showing `background task 0%` and the issue mentioned here in the output of the Language Support extension.


> I'm experiencing the same issue. Workaround for me was reverting "Language Support for Java(TM) by Red Hat" to the previous version.
> 
> This was causing compiler warnings to not appear which frankly makes the extension unusable.

Reverting to 1.39.0 fixes the issue.

**Comment by youhogeon** [comment]
If lowering the version of “Language Support for Java(TM) by Red Hat” is a hassle (and you don't want to), try searching for java in the extensions menu and switching to the trial version. It seems to work well (at least for me).

**Comment by Detelin-Yordanov-IBM** [comment]
We are experiencing the same issue, both workarounds (downgrading or upgrading) seem to work, thanks. However, if upgrading to e.g. 1.41.2025032208, we started seeing compile issues similar to:

```
Error occured while building workspace. Details: 
 message: The type sun.nio.ch.DirectBuffer is not accessible; code: 1677866
```

We have already configured `compileJava` task to expose these:

```
compileJava {
    options.compilerArgs << '--add-exports=java.base/sun.nio.ch=ALL-UNNAMED'
    options.compilerArgs << '--add-exports=java.base/jdk.internal.ref=ALL-UNNAMED'
}
```

So not sure what is the problem - perhaps some regression or other change in latest 1.41 version of Language Support for Java extension. Issue looks similar to https://github.com/microsoft/vscode-java-pack/issues/1080 which is still open, but we did not encounter this issue with previous 1.39 version of the extension

**Comment by rgrunber** [comment]
@jdneo , looks like a fix for this should definitely be included before doing a release of vscode-gradle. It really should be just a one-liner update of the method signature. Might need to figure out if the "release version" (new required parameter) is stored somewhere that's accessible.

**Comment by jdneo** [comment]
@rgrunber I just published a nightly build for gradle extension (3.17.2025032611 ), I tested locally it works fine. But in case that I misunderstood the issue, would be helpful if you can do some quick verification as well. Thanks! :)

**Comment by rgrunber** [comment]
I don't think I was actually able to reproduce the issue. I probably just looked at the stacktrace and reasoned that if that code runs, the error would happen.

**Comment by FabianGolembiewski-sp** [comment]
When this problem will be fixed? It still occurs with latest "Language Support for Java" version.

**Comment by rgrunber** [comment]
Nothing was done for this in vscode-java. It's fixed in the pre-release builds of  [`vscjava.vscode-gradle`](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle). Anything newer than `3.17.2025032611` has the fix.

**Comment by DrewCCannedy** [comment]
When will this be included in an actual release? And why hasn't there been a release in a year?

**Comment by rgrunber** [comment]
I don't think this extension has had much maintenance work in the past little while : https://github.com/microsoft/vscode-gradle/graphs/contributors?from=2025-02-15 but going from that, maybe @chagong will have something planned soon. I do see some recent work has gone in that might be worth an update.

**Comment by jeanbza** [comment]
+1, still running into this issue today and would love to know if a fix can be pushed to released track. :)
